p8105_hw1_jy3270
================
Jingya Yu
2022-09-22

## Useful library

``` r
library(tidyverse)
```

    ## ── Attaching packages ────────────────────────────────── tidyverse 1.3.2.9000 ──
    ## ✔ ggplot2   3.3.6      ✔ dplyr     1.0.10
    ## ✔ tibble    3.1.8      ✔ stringr   1.4.1 
    ## ✔ tidyr     1.2.1      ✔ forcats   0.5.2 
    ## ✔ readr     2.1.2      ✔ lubridate 1.8.0 
    ## ✔ purrr     0.3.4      
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
library(palmerpenguins)
library(ggplot2)
```

## Problem 1

#### Download and load the penguins dataset

``` r
# install.packages("palmerpenguins")
data("penguins", package = "palmerpenguins")
```

#### Short description of the dataset

``` r
summary(penguins)
```

    ##       species          island    bill_length_mm  bill_depth_mm  
    ##  Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
    ##  Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
    ##  Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
    ##                                  Mean   :43.92   Mean   :17.15  
    ##                                  3rd Qu.:48.50   3rd Qu.:18.70  
    ##                                  Max.   :59.60   Max.   :21.50  
    ##                                  NA's   :2       NA's   :2      
    ##  flipper_length_mm  body_mass_g       sex           year     
    ##  Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
    ##  1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
    ##  Median :197.0     Median :4050   NA's  : 11   Median :2008  
    ##  Mean   :200.9     Mean   :4202                Mean   :2008  
    ##  3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
    ##  Max.   :231.0     Max.   :6300                Max.   :2009  
    ##  NA's   :2         NA's   :2

``` r
head(penguins)
```

    ## # A tibble: 6 × 8
    ##   species island    bill_length_mm bill_depth_mm flipper_l…¹ body_…² sex    year
    ##   <fct>   <fct>              <dbl>         <dbl>       <int>   <int> <fct> <int>
    ## 1 Adelie  Torgersen           39.1          18.7         181    3750 male   2007
    ## 2 Adelie  Torgersen           39.5          17.4         186    3800 fema…  2007
    ## 3 Adelie  Torgersen           40.3          18           195    3250 fema…  2007
    ## 4 Adelie  Torgersen           NA            NA            NA      NA <NA>   2007
    ## 5 Adelie  Torgersen           36.7          19.3         193    3450 fema…  2007
    ## 6 Adelie  Torgersen           39.3          20.6         190    3650 male   2007
    ## # … with abbreviated variable names ¹​flipper_length_mm, ²​body_mass_g

``` r
mean(penguins$flipper_length_mm, na.rm = TRUE)
```

    ## [1] 200.9152

``` r
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

### Summary of Dataset:

The `penguin` dataset consists of 344 rows and 8 columns. The dataset
reviews the species of the penguins, the island where the penguin is
located, penguin’s bill length (mm), bill depth(mm), flipper length
(mm), body mass (g), sex, and the year the measurement was taken. There
are 3 categories under `species` variable: Adelie, Chinstrap, and
Gentoo, and the rangeof the variable `bill_length_mm` is32.1 mm to 59.6
mm, and its mean is 43.9219298 mm. At the same time, the variable
`flipper_length_mm` has a range of 172 mm to 231 mm, its mean is
200.9152047 mm. The dataset has 344 rows and 8 columns in total.

##### Make plot for `penguin` Dataset:

``` r
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point()
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8105_hw1_jy3270_files/figure-gfm/unnamed-chunk-4-1.png)<!-- -->

``` r
ggsave("flipperlength_vs_billlength.pdf", w = 6, h = 4)
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

## Problem 2

#### Create Data Frame

``` r
numeric_vector = rnorm(10)
logical_vector = numeric_vector > 0
character_vector = c('F', 'D', 'A', 'B', 'O', 'L', 'Y', 'P', 'S', 'A')
factor_vector = factor(c('small', 'large', 'medium', 'small', 'medium', 'large', 'large', 'small', 'medium', 'small'))
problem2_df = tibble(
  numeric_vector,
  logical_vector,
  character_vector,
  factor_vector)
problem2_df
```

    ## # A tibble: 10 × 4
    ##    numeric_vector logical_vector character_vector factor_vector
    ##             <dbl> <lgl>          <chr>            <fct>        
    ##  1         0.0824 TRUE           F                small        
    ##  2        -1.85   FALSE          D                large        
    ##  3        -0.742  FALSE          A                medium       
    ##  4        -0.281  FALSE          B                small        
    ##  5        -0.187  FALSE          O                medium       
    ##  6         0.445  TRUE           L                large        
    ##  7        -0.167  FALSE          Y                large        
    ##  8        -0.521  FALSE          P                small        
    ##  9        -0.160  FALSE          S                medium       
    ## 10        -1.11   FALSE          A                small

#### Mean of variables

``` r
mean(pull(.data = problem2_df, numeric_vector))
```

    ## [1] -0.4488314

``` r
mean(pull(.data = problem2_df, logical_vector))
```

    ## [1] 0.2

``` r
mean(pull(.data = problem2_df, character_vector))
```

    ## Warning in mean.default(pull(.data = problem2_df, character_vector)): argument
    ## is not numeric or logical: returning NA

    ## [1] NA

``` r
mean(pull(.data = problem2_df, factor_vector))
```

    ## Warning in mean.default(pull(.data = problem2_df, factor_vector)): argument is
    ## not numeric or logical: returning NA

    ## [1] NA

We can successfully compute the mean of the numeric and logical vectors
but the character and factor vectors produced a warming and result in
`NA` as the output.

##### Using `as.numeric` to convert variable types:

``` r
as.numeric(problem2_df$logical_vector)
as.numeric(problem2_df$character_vector)
as.numeric(problem2_df$factor_vector)
```

The `as.numeric` function converted the `logical_vector` variable to a
binary variable with only 0 and 1, which represent FALSE and TRUE, so
the average number will be a number between 0 and 1.

At the same time, the `factor_vector` variable was converted to 1’s,
2’s, and 3’s representing three different levels. The values
representing the levels of `factor_vector` were assigned as ‘large’ = 1,
‘medium’ = 2, ‘small’ = 3. Similar to the `logic_vector` variable, R
convert the variable using `as.numeric` in order to make calculation and
the factors were assigned alphabetically, but before the conversion R
could make the computation and resulted in warning.

The `character_vector` variable were failed to be converted using the
`as.numeric` function, thus showing warning and introducing NA by
coercion.
